### ISSUE TITLE
The Question class should be implemented by myself?

### ISSUE THREAD

**Issue by reeingal** [GeraudLuku/Squezap#1]
Hello, I am studying this project. And when I build the project, it output the message, could not found com.geraud.quizzapp.Model.Question. There is not exist the Question.java in com.geraud.quizzapp.Model, so should I implement class Question by mysite? Thank you.

**Comment by GeraudLuku** [comment]
Thank you for bringing this up.. 

did u try rebuilding the project?

did you check the models sub folder to be sure that the questions class doesn't exist?

if it doesn't exist i can send you the class implementation

**Comment by reeingal** [comment]
> 
> 
> Thank you for bringing this up..
> 
> did u try rebuilding the project?
> 
> did you check the models sub folder to be sure that the questions class doesn't exist?
> 
> if it doesn't exist i can send you the class implementation

Thank you for your reply. 

I check sub folder, and the Question class actually doesn't exist. 

I would be obliged if you could send the class file to me(reeingal@protonmail.com), or push it to the repo. 

Thank you.

**Comment by GeraudLuku** [comment]
okay i am sending it via email.. i have confirmed its not found in the repository

will update the repo later

thanks

**Comment by GeraudLuku** [comment]
i just uploaded the questions class
